spring:
  application:
    name: api-gateway-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8787/eureka}

zuul:
  routes:
    serviceA:
      path: /**
      service-id: serviceA

