spring:
  application:
    name: zuul-gateway

server:
  port: 8100

zuul:
  routes:
    serviceA:
      path: /service/**
      serviceId: serviceA

ribbon:
  eureka:
    enabled: false

serviceA:
  ribbon:
    listOfServers: http://localhost:8081, http://localhost:8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
